# Execute below command to run this playbook
# ansible-playbook address-object.yml --diff


--- 
- name: Create an address object in Panorama 
  hosts: panorama
  connection: local
  gather_facts: false
#  ignore_errors: true
 
  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Create Object of an IP Address
      panos_address_object:
        provider: '{{ pan_provider }}'
        name: 'H-9.9.9.9-32'
        value: '9.9.9.9/32'
        description: 'Host Object 9.9.9.9'
        device_group: 'shared'  
        tag: ['Prod']
        
    - name: Create IP Address Range Object
      panos_address_object:
        provider: '{{ pan_provider }}'
        name: 'Range-IP-Address'
        address_type: 'ip-range'
        value: '1.1.1.1-1.1.1.100'
        description: 'Range of IP Addresses'
        device_group: 'shared'
        tag: ['UAT']
    
    - name: Create FQDN Object
      panos_address_object:
        provider: '{{ pan_provider }}'
        name: 'FQDN-example.com'
        address_type: 'fqdn'
        value: 'www.example.com'
        description: 'FQDN Based Object'
        device_group: 'shared'
        
    - name: Update an existing object
      panos_address_object:
        provider: '{{ pan_provider }}'
        name: 'H-9.9.9.9-32'
        value: '9.9.9.10/32'
        state: 'replaced'
        device_group: 'shared'  
        
    - name: Delete an existing object
      panos_address_object:
        provider: '{{ pan_provider }}'
        name: 'H-9.9.9.9-32'
        state: 'absent'
        device_group: 'shared'  
