# Execute below command to run this playbook
# ansible-playbook address-object-group-gather.yml

--- 
- name: Gather the values of an existing address object group
  hosts: panorama
  connection: local
  gather_facts: false
 
  collections:
    - paloaltonetworks.panos    

  tasks:
    - name: Get all members of the object group 
      panos_address_group:
        provider: '{{ pan_provider }}'
        state: 'gathered'
        name: 'dns-object-group'
      register: output
      
    - debug:
        var: output.gathered.static_value
