# Execute below command to run this playbook
# ansible-playbook address-object-group-delete.yml --diff

--- 
- name: Delete an existing address object group in Panorama 
  hosts: panorama
  connection: local
  gather_facts: false
#  ignore_errors: true
 
  collections:
    - paloaltonetworks.panos

  tasks:
      - name: Delete DNS object group
      panos_address_group:
        provider: '{{ pan_provider }}'
        name: 'dns-object-group'
        state: 'absent'
  
    - name: Delete DNS Object-1
      panos_address_object:
        provider: '{{ pan_provider }}'
        name: 'H-8.8.8.8-32'
        state: 'absent'      

    - name: Delete DNS Object-2
      panos_address_object:
        provider: '{{ pan_provider }}'
        name: 'H-8.8.4.4-32'
        state: 'absent'

